### ISSUE TITLE
Apple docs say you should just ignore this error

### ISSUE THREAD

**Issue by MrFuFuFu** [PromiseKit/CoreLocation#24]
Hi there, 

When I tried to get current location in my Simulator. Surely, it will gets wrong if Simulator doesn't have current location. So it will jump into this function and then runs into the `if` condition. I see the note. Could you explain that `// Apple docs say you should just ignore this error`? Or could you provide where the Apple docs says that? I didn't find it in [CLError.locationUnknown](https://developer.apple.com/documentation/corelocation/clerror/2320673-locationunknown).

Because the Promise didn't get rejected if the code run into this `if` condition in my Simulator.

Many thanks.

```swift
    @objc func locationManager(_ manager: CLLocationManager, didFailWithError error: Error) {
        let (domain, code) = { ($0.domain, $0.code) }(error as NSError)
        if code == CLError.locationUnknown.rawValue && domain == kCLErrorDomain {
            // Apple docs say you should just ignore this error
        } else {
            seal.reject(error)
        }
    }
```

By the way, I chose the location as `City Run` or `City Bicycle Ride` or `Freeway Drive` in Simulator's Debug

**Comment by mxcl** [comment]
https://developer.apple.com/documentation/corelocation/cllocationmanagerdelegate/1423786-locationmanager?language=objc

This error tends to happen in the simulator and it means you have not set the simulator to provide a location.

**Comment by MrFuFuFu** [comment]
Cool, Thanks mate.

**Comment by mxcl** [comment]
Thanks 👍🏻

If you found my work helpful, please consider [supporting its development](https://patreon.com/mxcl).
