### ISSUE TITLE
Update LocationManager Parameters

### ISSUE THREAD

**Issue by martheli** [PromiseKit/CoreLocation#29]
Is there a way to set `LocationManager` parameters like `allowsBackgroundLocationUpdates` or `pauseLocationUpdatesAutomatically`? If this is possible via the `satisfying` block, can an example be provided?

**Comment by mxcl** [comment]
It is not.

**Comment by mxcl** [comment]
Really we should make our promise an instance member. We’ve done it in other places. We *would* have to take over the delegate however, which is the main reason it is `static`.
