### ISSUE TITLE
When no string is included in info.plist, never fulfils or rejects. *In swift

### ISSUE THREAD

**Issue by Vazmista** [PromiseKit/CoreLocation#6]
I've noticed that if the application doesn't have either whenInUse or always strings in the info.plist, the promise never gets fulfilled (or rejected), causing that promise to never return. I would have thought it would reject with some kind of error?

**Comment by mxcl** [comment]
Which promise?

**Comment by mxcl** [comment]
As far as I can tell, there's nothing I can do.

Apple do not call the error handler for this situation, and PromiseKit is merely a wrapper. If the underlying thing doesn't call the error handler then we cannot notify you of the error either.

**Comment by mxcl** [comment]
Cannot fix.
